apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: sidecar-svc-csr
spec:
  request: ${CSR_PLACEHOLDER}
  usages:
  - server auth
  - digital signature
  - key encipherment
  groups:
  - system:authenticated
