apiVersion: v1
kind: Service
metadata:
  name: sidecar-svc
  namespace: sidecar-injection
spec:
  ports:
  - name: sidecar-port
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: sidecar-injection
