apiVersion: v1
kind: ConfigMap
metadata:
  name: sidecar-cm
  namespace: sidecar-injection
data:
  sidecarspec.yaml: |
    containers:
    - name: nginx
      image: nginx:stable-alpine
      imagePullPolicy: IfNotPresent
      ports:
      - name: http
        containerPort: 80
        protocol: TCP
      volumeMounts:
      - name: conf
        mountPath: /etc/nginx/nginx.conf
        subPath: nginx.conf
        readOnly: true
    volumes:
    - name: conf
      configMap:
        name: nginx-config
